server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /products {
        proxy_pass http://alb-backend-1062806086.us-east-1.elb.amazonaws.com;
    }
}